version: '3.9'

services:
  app1:
    container_name: app1
    build: ./app
    environment:
      - APP_NAME=App1

  app2:
    build: ./app
    container_name: app2
    environment:
      - APP_NAME=App2

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
